name: multiply-ui

channels:
  - conda-forge
  - defaults

dependencies:
  - bokeh =1.0.4
  - click =7.0
  - ipyleaflet = 0.10.4
  - ipywidgets =7.4.2
  - jupyterlab =0.35.4
  - python =3.7.2
  - tornado =5.1.1
  - traitlets = 4.3.2
  - xarray =0.10.8
  # Testing
  - pytest
  - pytest-cov
